[phases.setup]
# use top-level poetry instead of the deprecated python311Packages.poetry
nixPkgs = ["python311", "poetry", "python311Packages.pip"]

[phases.build]
cmds = ["cd backend && poetry install --no-interaction --no-ansi"]

[start]
cmd = "cd backend && poetry run python serve.py"